on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
name: Build_release


env:
  IMAGE_NAME: labulaka522/crocodile

jobs:
  build:
    name: Build And Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22.1'
          cache-dependency-path: "**/go.sum"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release ${{ github.ref }}
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Build All Release
        run: |
          make frontend
          make bindata
          make clean
          make vet
          make swag
          make build_all
      - name: Upload file to release
        uses: labulaka521/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
